# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ats_test4' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ats_test4
    pod 'MobileVLCKit'

    inherit! :search_paths

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

end
