# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ats_test4' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ats_test4
  #  pod 'MobileVLCKit'
    pod 'Firebase/Core'
    inherit! :search_paths




end
